/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'smartcore-js.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'smartcore-js.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = __nodePath.resolve('@saltcorn/smartcore-js-wasm32-wasi')
  } catch {
    throw new Error('Cannot find smartcore-js.wasm32-wasi.wasm file, and @saltcorn/smartcore-js-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.AccuracyF32 = __napiModule.exports.AccuracyF32
module.exports.Accuracyf32 = __napiModule.exports.Accuracyf32
module.exports.AccuracyF64 = __napiModule.exports.AccuracyF64
module.exports.Accuracyf64 = __napiModule.exports.Accuracyf64
module.exports.AccuracyU32 = __napiModule.exports.AccuracyU32
module.exports.Accuracyu32 = __napiModule.exports.Accuracyu32
module.exports.AUCF32 = __napiModule.exports.AUCF32
module.exports.AUCf32 = __napiModule.exports.AUCf32
module.exports.AUCF64 = __napiModule.exports.AUCF64
module.exports.AUCf64 = __napiModule.exports.AUCf64
module.exports.Boston = __napiModule.exports.Boston
module.exports.BreastCancer = __napiModule.exports.BreastCancer
module.exports.dataset = __napiModule.exports.dataset
module.exports.Dataset = __napiModule.exports.Dataset
module.exports.DatasetF32F32 = __napiModule.exports.DatasetF32F32
module.exports.DatasetF32U32 = __napiModule.exports.DatasetF32U32
module.exports.DenseMatrixF32 = __napiModule.exports.DenseMatrixF32
module.exports.DenseMatrixF64 = __napiModule.exports.DenseMatrixF64
module.exports.Diabetes = __napiModule.exports.Diabetes
module.exports.Digits = __napiModule.exports.Digits
module.exports.Euclidianf32 = __napiModule.exports.Euclidianf32
module.exports.EuclidianF32 = __napiModule.exports.EuclidianF32
module.exports.Euclidianf64 = __napiModule.exports.Euclidianf64
module.exports.EuclidianF64 = __napiModule.exports.EuclidianF64
module.exports.Euclidiani32 = __napiModule.exports.Euclidiani32
module.exports.EuclidianI32 = __napiModule.exports.EuclidianI32
module.exports.Euclidiani64 = __napiModule.exports.Euclidiani64
module.exports.EuclidianI64 = __napiModule.exports.EuclidianI64
module.exports.Euclidianu32 = __napiModule.exports.Euclidianu32
module.exports.EuclidianU32 = __napiModule.exports.EuclidianU32
module.exports.Euclidianu64 = __napiModule.exports.Euclidianu64
module.exports.EuclidianU64 = __napiModule.exports.EuclidianU64
module.exports.F1F32 = __napiModule.exports.F1F32
module.exports.F1f32 = __napiModule.exports.F1f32
module.exports.F1F64 = __napiModule.exports.F1F64
module.exports.F1f64 = __napiModule.exports.F1f64
module.exports.Generator = __napiModule.exports.Generator
module.exports.HammingF32 = __napiModule.exports.HammingF32
module.exports.HammingF64 = __napiModule.exports.HammingF64
module.exports.HammingI32 = __napiModule.exports.HammingI32
module.exports.HammingI64 = __napiModule.exports.HammingI64
module.exports.HammingU32 = __napiModule.exports.HammingU32
module.exports.HammingU64 = __napiModule.exports.HammingU64
module.exports.HCVScoreU32 = __napiModule.exports.HCVScoreU32
module.exports.HCVScoreu32 = __napiModule.exports.HCVScoreu32
module.exports.HCVScoreU64 = __napiModule.exports.HCVScoreU64
module.exports.HCVScoreu64 = __napiModule.exports.HCVScoreu64
module.exports.Iris = __napiModule.exports.Iris
module.exports.KNNClassifierF32U32 = __napiModule.exports.KNNClassifierF32U32
module.exports.KNNRegressorF32F32 = __napiModule.exports.KNNRegressorF32F32
module.exports.KNNRegressorF32U32 = __napiModule.exports.KNNRegressorF32U32
module.exports.KNNRegressorParametersF32EuclidianF32 = __napiModule.exports.KNNRegressorParametersF32EuclidianF32
module.exports.EuclidianF32KNNRegressorParametersf32 = __napiModule.exports.EuclidianF32KNNRegressorParametersf32
module.exports.KNNRegressorParametersF32HammingF32 = __napiModule.exports.KNNRegressorParametersF32HammingF32
module.exports.HammingF32KNNRegressorParametersf32 = __napiModule.exports.HammingF32KNNRegressorParametersf32
module.exports.LassoF32F32 = __napiModule.exports.LassoF32F32
module.exports.Lassof32f32 = __napiModule.exports.Lassof32f32
module.exports.LassoF32U32 = __napiModule.exports.LassoF32U32
module.exports.Lassof32u32 = __napiModule.exports.Lassof32u32
module.exports.LassoF64F64 = __napiModule.exports.LassoF64F64
module.exports.Lassof64f64 = __napiModule.exports.Lassof64f64
module.exports.LassoParameters = __napiModule.exports.LassoParameters
module.exports.LinearRegressionF32F32 = __napiModule.exports.LinearRegressionF32F32
module.exports.LinearRegressionf32f32 = __napiModule.exports.LinearRegressionf32f32
module.exports.LinearRegressionF32U32 = __napiModule.exports.LinearRegressionF32U32
module.exports.LinearRegressionf32u32 = __napiModule.exports.LinearRegressionf32u32
module.exports.LinearRegressionF64F64 = __napiModule.exports.LinearRegressionF64F64
module.exports.LinearRegressionf64f64 = __napiModule.exports.LinearRegressionf64f64
module.exports.LinearRegressionParameters = __napiModule.exports.LinearRegressionParameters
module.exports.LogisticRegressionF32U32 = __napiModule.exports.LogisticRegressionF32U32
module.exports.LogisticRegressionf32u32 = __napiModule.exports.LogisticRegressionf32u32
module.exports.LogisticRegressionF64U64 = __napiModule.exports.LogisticRegressionF64U64
module.exports.LogisticRegressionf64u64 = __napiModule.exports.LogisticRegressionf64u64
module.exports.LogisticRegressionParametersF32 = __napiModule.exports.LogisticRegressionParametersF32
module.exports.LogisticRegressionParametersf32 = __napiModule.exports.LogisticRegressionParametersf32
module.exports.LogisticRegressionParametersF64 = __napiModule.exports.LogisticRegressionParametersF64
module.exports.LogisticRegressionParametersf64 = __napiModule.exports.LogisticRegressionParametersf64
module.exports.MahalanobisF64 = __napiModule.exports.MahalanobisF64
module.exports.ManhattanF32 = __napiModule.exports.ManhattanF32
module.exports.ManhattanF64 = __napiModule.exports.ManhattanF64
module.exports.ManhattanI32 = __napiModule.exports.ManhattanI32
module.exports.ManhattanI64 = __napiModule.exports.ManhattanI64
module.exports.ManhattanU32 = __napiModule.exports.ManhattanU32
module.exports.ManhattanU64 = __napiModule.exports.ManhattanU64
module.exports.MeanAbsoluteErrorF32 = __napiModule.exports.MeanAbsoluteErrorF32
module.exports.MeanAbsoluteErrorf32 = __napiModule.exports.MeanAbsoluteErrorf32
module.exports.MeanAbsoluteErrorF64 = __napiModule.exports.MeanAbsoluteErrorF64
module.exports.MeanAbsoluteErrorf64 = __napiModule.exports.MeanAbsoluteErrorf64
module.exports.MeanSquareErrorF32 = __napiModule.exports.MeanSquareErrorF32
module.exports.MeanSquareErrorf32 = __napiModule.exports.MeanSquareErrorf32
module.exports.MeanSquareErrorF64 = __napiModule.exports.MeanSquareErrorF64
module.exports.MeanSquareErrorf64 = __napiModule.exports.MeanSquareErrorf64
module.exports.MinkowskiF32 = __napiModule.exports.MinkowskiF32
module.exports.MinkowskiF64 = __napiModule.exports.MinkowskiF64
module.exports.MinkowskiI32 = __napiModule.exports.MinkowskiI32
module.exports.MinkowskiI64 = __napiModule.exports.MinkowskiI64
module.exports.MinkowskiU32 = __napiModule.exports.MinkowskiU32
module.exports.MinkowskiU64 = __napiModule.exports.MinkowskiU64
module.exports.PCAF32 = __napiModule.exports.PCAF32
module.exports.PCAf32 = __napiModule.exports.PCAf32
module.exports.PCAF64 = __napiModule.exports.PCAF64
module.exports.PCAf64 = __napiModule.exports.PCAf64
module.exports.PCAParameters = __napiModule.exports.PCAParameters
module.exports.PrecisionF32 = __napiModule.exports.PrecisionF32
module.exports.Precisionf32 = __napiModule.exports.Precisionf32
module.exports.PrecisionF64 = __napiModule.exports.PrecisionF64
module.exports.Precisionf64 = __napiModule.exports.Precisionf64
module.exports.R2U32 = __napiModule.exports.R2U32
module.exports.R2u32 = __napiModule.exports.R2u32
module.exports.R2U64 = __napiModule.exports.R2U64
module.exports.R2u64 = __napiModule.exports.R2u64
module.exports.RecallF32 = __napiModule.exports.RecallF32
module.exports.Recallf32 = __napiModule.exports.Recallf32
module.exports.RecallF64 = __napiModule.exports.RecallF64
module.exports.Recallf64 = __napiModule.exports.Recallf64
module.exports.RidgeRegressionF32F32 = __napiModule.exports.RidgeRegressionF32F32
module.exports.RidgeRegressionf32f32 = __napiModule.exports.RidgeRegressionf32f32
module.exports.RidgeRegressionF32U32 = __napiModule.exports.RidgeRegressionF32U32
module.exports.RidgeRegressionf32u32 = __napiModule.exports.RidgeRegressionf32u32
module.exports.RidgeRegressionF64F64 = __napiModule.exports.RidgeRegressionF64F64
module.exports.RidgeRegressionf64f64 = __napiModule.exports.RidgeRegressionf64f64
module.exports.RidgeRegressionParametersF32 = __napiModule.exports.RidgeRegressionParametersF32
module.exports.RidgeRegressionParametersf32 = __napiModule.exports.RidgeRegressionParametersf32
module.exports.RidgeRegressionParametersF64 = __napiModule.exports.RidgeRegressionParametersF64
module.exports.RidgeRegressionParametersf64 = __napiModule.exports.RidgeRegressionParametersf64
module.exports.KNNAlgorithmName = __napiModule.exports.KNNAlgorithmName
module.exports.KNNWeightFunction = __napiModule.exports.KNNWeightFunction
module.exports.LinearRegressionSolverName = __napiModule.exports.LinearRegressionSolverName
module.exports.LogisticRegressionSolverName = __napiModule.exports.LogisticRegressionSolverName
module.exports.RidgeRegressionSolverName = __napiModule.exports.RidgeRegressionSolverName
module.exports.trainTestSplitF32F32 = __napiModule.exports.trainTestSplitF32F32
module.exports.trainTestSplitF32U32 = __napiModule.exports.trainTestSplitF32U32
module.exports.trainTestSplitF64F64 = __napiModule.exports.trainTestSplitF64F64
