"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PredictorProvidersMap = void 0;
const dbscan_f32_euclidian_f32_provider_js_1 = __importDefault(require("./dbscan_f32_euclidian_f32_provider.js"));
const dbscan_f32_mahalanobis_f32_provider_js_1 = __importDefault(require("./dbscan_f32_mahalanobis_f32_provider.js"));
const dbscan_f32_manhattan_f32_provider_js_1 = __importDefault(require("./dbscan_f32_manhattan_f32_provider.js"));
const dbscan_f32_minkowski_f32_provider_js_1 = __importDefault(require("./dbscan_f32_minkowski_f32_provider.js"));
const dbscan_f64_euclidian_f64_provider_js_1 = __importDefault(require("./dbscan_f64_euclidian_f64_provider.js"));
const dbscan_f64_mahalanobis_f64_provider_js_1 = __importDefault(require("./dbscan_f64_mahalanobis_f64_provider.js"));
const dbscan_f64_manhattan_f64_provider_js_1 = __importDefault(require("./dbscan_f64_manhattan_f64_provider.js"));
const dbscan_f64_minkowski_f64_provider_js_1 = __importDefault(require("./dbscan_f64_minkowski_f64_provider.js"));
const dbscan_u32_euclidian_u32_provider_js_1 = __importDefault(require("./dbscan_u32_euclidian_u32_provider.js"));
const dbscan_u32_manhattan_u32_provider_js_1 = __importDefault(require("./dbscan_u32_manhattan_u32_provider.js"));
const dbscan_i32_euclidian_i32_provider_js_1 = __importDefault(require("./dbscan_i32_euclidian_i32_provider.js"));
const dbscan_i32_hamming_i32_provider_js_1 = __importDefault(require("./dbscan_i32_hamming_i32_provider.js"));
const dbscan_i32_manhattan_i32_provider_js_1 = __importDefault(require("./dbscan_i32_manhattan_i32_provider.js"));
const dbscan_i32_minkowski_i32_provider_js_1 = __importDefault(require("./dbscan_i32_minkowski_i32_provider.js"));
const dbscan_i64_euclidian_i64_provider_js_1 = __importDefault(require("./dbscan_i64_euclidian_i64_provider.js"));
const dbscan_i64_manhattan_i64_provider_js_1 = __importDefault(require("./dbscan_i64_manhattan_i64_provider.js"));
const dbscan_i64_minkowski_i64_provider_js_1 = __importDefault(require("./dbscan_i64_minkowski_i64_provider.js"));
const dbscan_u16_euclidian_u16_provider_js_1 = __importDefault(require("./dbscan_u16_euclidian_u16_provider.js"));
const dbscan_u16_hamming_u16_provider_js_1 = __importDefault(require("./dbscan_u16_hamming_u16_provider.js"));
const dbscan_u8_euclidian_u8_provider_js_1 = __importDefault(require("./dbscan_u8_euclidian_u8_provider.js"));
const dbscan_u8_hamming_u8_provider_js_1 = __importDefault(require("./dbscan_u8_hamming_u8_provider.js"));
const dbscan_u64_euclidian_u64_provider_js_1 = __importDefault(require("./dbscan_u64_euclidian_u64_provider.js"));
const dbscan_u64_manhattan_u64_provider_js_1 = __importDefault(require("./dbscan_u64_manhattan_u64_provider.js"));
const F32PredictorProvidersMap = new Map();
F32PredictorProvidersMap.set('euclidian', new dbscan_f32_euclidian_f32_provider_js_1.default());
F32PredictorProvidersMap.set('mahalanobis', new dbscan_f32_mahalanobis_f32_provider_js_1.default());
F32PredictorProvidersMap.set('manhattan', new dbscan_f32_manhattan_f32_provider_js_1.default());
F32PredictorProvidersMap.set('minkowski', new dbscan_f32_minkowski_f32_provider_js_1.default());
const F64PredictorProvidersMap = new Map();
F64PredictorProvidersMap.set('euclidian', new dbscan_f64_euclidian_f64_provider_js_1.default());
F64PredictorProvidersMap.set('mahalanobis', new dbscan_f64_mahalanobis_f64_provider_js_1.default());
F64PredictorProvidersMap.set('manhattan', new dbscan_f64_manhattan_f64_provider_js_1.default());
F64PredictorProvidersMap.set('minkowski', new dbscan_f64_minkowski_f64_provider_js_1.default());
const U32PredictorProvidersMap = new Map();
U32PredictorProvidersMap.set('euclidian', new dbscan_u32_euclidian_u32_provider_js_1.default());
U32PredictorProvidersMap.set('manhattan', new dbscan_u32_manhattan_u32_provider_js_1.default());
const I32PredictorProvidersMap = new Map();
I32PredictorProvidersMap.set('euclidian', new dbscan_i32_euclidian_i32_provider_js_1.default());
I32PredictorProvidersMap.set('hamming', new dbscan_i32_hamming_i32_provider_js_1.default());
I32PredictorProvidersMap.set('manhattan', new dbscan_i32_manhattan_i32_provider_js_1.default());
I32PredictorProvidersMap.set('minkowski', new dbscan_i32_minkowski_i32_provider_js_1.default());
const I64PredictorProvidersMap = new Map();
I64PredictorProvidersMap.set('euclidian', new dbscan_i64_euclidian_i64_provider_js_1.default());
I64PredictorProvidersMap.set('manhattan', new dbscan_i64_manhattan_i64_provider_js_1.default());
I64PredictorProvidersMap.set('minkowski', new dbscan_i64_minkowski_i64_provider_js_1.default());
const U16PredictorProvidersMap = new Map();
U16PredictorProvidersMap.set('euclidian', new dbscan_u16_euclidian_u16_provider_js_1.default());
U16PredictorProvidersMap.set('hamming', new dbscan_u16_hamming_u16_provider_js_1.default());
const U8PredictorProvidersMap = new Map();
U8PredictorProvidersMap.set('euclidian', new dbscan_u8_euclidian_u8_provider_js_1.default());
U8PredictorProvidersMap.set('hamming', new dbscan_u8_hamming_u8_provider_js_1.default());
const U64PredictorProvidersMap = new Map();
U64PredictorProvidersMap.set('euclidian', new dbscan_u64_euclidian_u64_provider_js_1.default());
U64PredictorProvidersMap.set('manhattan', new dbscan_u64_manhattan_u64_provider_js_1.default());
const PredictorProvidersMap = new Map();
exports.PredictorProvidersMap = PredictorProvidersMap;
PredictorProvidersMap.set('f32', F32PredictorProvidersMap);
PredictorProvidersMap.set('f64', F64PredictorProvidersMap);
PredictorProvidersMap.set('u32', U32PredictorProvidersMap);
PredictorProvidersMap.set('i32', I32PredictorProvidersMap);
PredictorProvidersMap.set('i64', I64PredictorProvidersMap);
PredictorProvidersMap.set('u16', U16PredictorProvidersMap);
PredictorProvidersMap.set('u8', U8PredictorProvidersMap);
PredictorProvidersMap.set('u64', U64PredictorProvidersMap);
