"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PredictorProvidersMap = void 0;
const kmeans_f32_i32_provider_js_1 = __importDefault(require("./kmeans_f32_i32_provider.js"));
const kmeans_f32_i64_provider_js_1 = __importDefault(require("./kmeans_f32_i64_provider.js"));
const kmeans_f64_i32_provider_js_1 = __importDefault(require("./kmeans_f64_i32_provider.js"));
const kmeans_f64_i64_provider_js_1 = __importDefault(require("./kmeans_f64_i64_provider.js"));
const kmeans_u32_i32_provider_js_1 = __importDefault(require("./kmeans_u32_i32_provider.js"));
const kmeans_u32_i64_provider_js_1 = __importDefault(require("./kmeans_u32_i64_provider.js"));
const kmeans_i32_i32_provider_js_1 = __importDefault(require("./kmeans_i32_i32_provider.js"));
const kmeans_i32_i64_provider_js_1 = __importDefault(require("./kmeans_i32_i64_provider.js"));
const kmeans_u64_i32_provider_js_1 = __importDefault(require("./kmeans_u64_i32_provider.js"));
const kmeans_u64_i64_provider_js_1 = __importDefault(require("./kmeans_u64_i64_provider.js"));
const kmeans_i64_i32_provider_js_1 = __importDefault(require("./kmeans_i64_i32_provider.js"));
const kmeans_i64_i64_provider_js_1 = __importDefault(require("./kmeans_i64_i64_provider.js"));
const F32PredictorProvidersMap = new Map();
F32PredictorProvidersMap.set('i32', new kmeans_f32_i32_provider_js_1.default());
F32PredictorProvidersMap.set('i64', new kmeans_f32_i64_provider_js_1.default());
const F64PredictorProvidersMap = new Map();
F64PredictorProvidersMap.set('i32', new kmeans_f64_i32_provider_js_1.default());
F64PredictorProvidersMap.set('i64', new kmeans_f64_i64_provider_js_1.default());
const U32PredictorProvidersMap = new Map();
U32PredictorProvidersMap.set('i32', new kmeans_u32_i32_provider_js_1.default());
U32PredictorProvidersMap.set('i64', new kmeans_u32_i64_provider_js_1.default());
const I32PredictorProvidersMap = new Map();
I32PredictorProvidersMap.set('i32', new kmeans_i32_i32_provider_js_1.default());
I32PredictorProvidersMap.set('i64', new kmeans_i32_i64_provider_js_1.default());
const I64PredictorProvidersMap = new Map();
I64PredictorProvidersMap.set('i32', new kmeans_i64_i32_provider_js_1.default());
I64PredictorProvidersMap.set('i64', new kmeans_i64_i64_provider_js_1.default());
const U64PredictorProvidersMap = new Map();
U64PredictorProvidersMap.set('i32', new kmeans_u64_i32_provider_js_1.default());
U64PredictorProvidersMap.set('i64', new kmeans_u64_i64_provider_js_1.default());
const PredictorProvidersMap = new Map();
exports.PredictorProvidersMap = PredictorProvidersMap;
PredictorProvidersMap.set('f32', F32PredictorProvidersMap);
PredictorProvidersMap.set('f64', F64PredictorProvidersMap);
PredictorProvidersMap.set('u32', U32PredictorProvidersMap);
PredictorProvidersMap.set('i32', I32PredictorProvidersMap);
PredictorProvidersMap.set('i64', I64PredictorProvidersMap);
PredictorProvidersMap.set('u64', U64PredictorProvidersMap);
