pub mod algorithm;
pub mod cluster;
pub mod dataset;
pub mod decomposition;
pub mod dense_matrix;
mod deserialize_variant;
pub mod distance_type;
pub mod ensemble;
pub mod js_number;
pub mod linalg;
pub mod linear;
pub mod metrics;
pub mod model_selection;
pub mod naive_bayes;
pub mod neighbors;
pub mod preprocessing;
pub mod refs;
pub mod svm;
mod traits;
pub mod tree;
pub mod typed_array;
