/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'smartcore-js.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'smartcore-js.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = __nodePath.resolve('@saltcorn/smartcore-js-wasm32-wasi')
  } catch {
    throw new Error('Cannot find smartcore-js.wasm32-wasi.wasm file, and @saltcorn/smartcore-js-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.AccuracyF64 = __napiModule.exports.AccuracyF64
module.exports.Accuracyf64 = __napiModule.exports.Accuracyf64
module.exports.AccuracyI64 = __napiModule.exports.AccuracyI64
module.exports.Accuracyi64 = __napiModule.exports.Accuracyi64
module.exports.AUCF64 = __napiModule.exports.AUCF64
module.exports.AUCf64 = __napiModule.exports.AUCf64
module.exports.BernoulliNBF64U64 = __napiModule.exports.BernoulliNBF64U64
module.exports.BernoulliNBParametersF64 = __napiModule.exports.BernoulliNBParametersF64
module.exports.Boston = __napiModule.exports.Boston
module.exports.BreastCancer = __napiModule.exports.BreastCancer
module.exports.CategoricalNBParameters = __napiModule.exports.CategoricalNBParameters
module.exports.CategoricalNBU64 = __napiModule.exports.CategoricalNBU64
module.exports.CrossValidationResult = __napiModule.exports.CrossValidationResult
module.exports.dataset = __napiModule.exports.dataset
module.exports.Dataset = __napiModule.exports.Dataset
module.exports.DatasetF64F64 = __napiModule.exports.DatasetF64F64
module.exports.DatasetF64F64JsVecRef = __napiModule.exports.DatasetF64F64JsVecRef
module.exports.DatasetF64I64 = __napiModule.exports.DatasetF64I64
module.exports.DatasetF64I64JsVecRef = __napiModule.exports.DatasetF64I64JsVecRef
module.exports.DBSCANF64F64 = __napiModule.exports.DBSCANF64F64
module.exports.DecisionTreeClassifierI64I64 = __napiModule.exports.DecisionTreeClassifierI64I64
module.exports.DecisionTreeClassifierParameters = __napiModule.exports.DecisionTreeClassifierParameters
module.exports.DecisionTreeRegressorI64I64 = __napiModule.exports.DecisionTreeRegressorI64I64
module.exports.DecisionTreeRegressorParameters = __napiModule.exports.DecisionTreeRegressorParameters
module.exports.DenseMatrixF64 = __napiModule.exports.DenseMatrixF64
module.exports.DenseMatrixI64 = __napiModule.exports.DenseMatrixI64
module.exports.DenseMatrixU64 = __napiModule.exports.DenseMatrixU64
module.exports.Diabetes = __napiModule.exports.Diabetes
module.exports.Digits = __napiModule.exports.Digits
module.exports.ElasticNetF64F64 = __napiModule.exports.ElasticNetF64F64
module.exports.ElasticNetF64I64 = __napiModule.exports.ElasticNetF64I64
module.exports.ElasticNetParameters = __napiModule.exports.ElasticNetParameters
module.exports.EuclidianF64 = __napiModule.exports.EuclidianF64
module.exports.EuclidianF64DBSCANF64Parameters = __napiModule.exports.EuclidianF64DBSCANF64Parameters
module.exports.EuclidianI64 = __napiModule.exports.EuclidianI64
module.exports.ExtraTreesRegressorF64BigI64 = __napiModule.exports.ExtraTreesRegressorF64BigI64
module.exports.ExtraTreesRegressorF64F64 = __napiModule.exports.ExtraTreesRegressorF64F64
module.exports.ExtraTreesRegressorF64I64 = __napiModule.exports.ExtraTreesRegressorF64I64
module.exports.ExtraTreesRegressorParameters = __napiModule.exports.ExtraTreesRegressorParameters
module.exports.F1F64 = __napiModule.exports.F1F64
module.exports.F1f64 = __napiModule.exports.F1f64
module.exports.GaussianNBF64U64 = __napiModule.exports.GaussianNBF64U64
module.exports.GaussianNBParameters = __napiModule.exports.GaussianNBParameters
module.exports.Generator = __napiModule.exports.Generator
module.exports.HammingF64 = __napiModule.exports.HammingF64
module.exports.HammingF64DBSCANF64Parameters = __napiModule.exports.HammingF64DBSCANF64Parameters
module.exports.HammingI64 = __napiModule.exports.HammingI64
module.exports.HCVScoreI64 = __napiModule.exports.HCVScoreI64
module.exports.HCVScorei64 = __napiModule.exports.HCVScorei64
module.exports.Iris = __napiModule.exports.Iris
module.exports.JsBoxedArrayF32Ref = __napiModule.exports.JsBoxedArrayF32Ref
module.exports.JsBoxedArrayF64Ref = __napiModule.exports.JsBoxedArrayF64Ref
module.exports.JsDenseMatrixF64Ref = __napiModule.exports.JsDenseMatrixF64Ref
module.exports.JsVecF64Ref = __napiModule.exports.JsVecF64Ref
module.exports.JsVecI64Ref = __napiModule.exports.JsVecI64Ref
module.exports.Kernels = __napiModule.exports.Kernels
module.exports.KFold = __napiModule.exports.KFold
module.exports.KMeansF64BigI64 = __napiModule.exports.KMeansF64BigI64
module.exports.KMeansF64F64 = __napiModule.exports.KMeansF64F64
module.exports.KMeansF64I64 = __napiModule.exports.KMeansF64I64
module.exports.KMeansParameters = __napiModule.exports.KMeansParameters
module.exports.KNNClassifierF64I64 = __napiModule.exports.KNNClassifierF64I64
module.exports.KNNRegressorF64F64 = __napiModule.exports.KNNRegressorF64F64
module.exports.KNNRegressorF64I64 = __napiModule.exports.KNNRegressorF64I64
module.exports.KNNRegressorParametersF64EuclidianF64 = __napiModule.exports.KNNRegressorParametersF64EuclidianF64
module.exports.EuclidianF64KNNRegressorParametersF64 = __napiModule.exports.EuclidianF64KNNRegressorParametersF64
module.exports.KNNRegressorParametersF64HammingF64 = __napiModule.exports.KNNRegressorParametersF64HammingF64
module.exports.HammingF64KNNRegressorParametersF64 = __napiModule.exports.HammingF64KNNRegressorParametersF64
module.exports.LassoF64F64 = __napiModule.exports.LassoF64F64
module.exports.LassoF64I64 = __napiModule.exports.LassoF64I64
module.exports.LassoParameters = __napiModule.exports.LassoParameters
module.exports.LinearRegressionF64F64 = __napiModule.exports.LinearRegressionF64F64
module.exports.LinearRegressionF64I64 = __napiModule.exports.LinearRegressionF64I64
module.exports.LinearRegressionParameters = __napiModule.exports.LinearRegressionParameters
module.exports.LogisticRegressionF64BigI64 = __napiModule.exports.LogisticRegressionF64BigI64
module.exports.LogisticRegressionF64I64 = __napiModule.exports.LogisticRegressionF64I64
module.exports.LogisticRegressionParametersF64 = __napiModule.exports.LogisticRegressionParametersF64
module.exports.MahalanobisF64 = __napiModule.exports.MahalanobisF64
module.exports.MahalanobisF64DBSCANF64Parameters = __napiModule.exports.MahalanobisF64DBSCANF64Parameters
module.exports.ManhattanF64 = __napiModule.exports.ManhattanF64
module.exports.ManhattanF64DBSCANF64Parameters = __napiModule.exports.ManhattanF64DBSCANF64Parameters
module.exports.ManhattanI64 = __napiModule.exports.ManhattanI64
module.exports.MeanAbsoluteErrorF64 = __napiModule.exports.MeanAbsoluteErrorF64
module.exports.MeanAbsoluteErrorf64 = __napiModule.exports.MeanAbsoluteErrorf64
module.exports.MeanSquareErrorF64 = __napiModule.exports.MeanSquareErrorF64
module.exports.MeanSquareErrorf64 = __napiModule.exports.MeanSquareErrorf64
module.exports.MinkowskiF64 = __napiModule.exports.MinkowskiF64
module.exports.MinkowskiF64DBSCANF64Parameters = __napiModule.exports.MinkowskiF64DBSCANF64Parameters
module.exports.MinkowskiI64 = __napiModule.exports.MinkowskiI64
module.exports.MultinomialNBParameters = __napiModule.exports.MultinomialNBParameters
module.exports.MultinomialNBU64U64 = __napiModule.exports.MultinomialNBU64U64
module.exports.OneHotEncoderF64 = __napiModule.exports.OneHotEncoderF64
module.exports.OneHotEncoderParameters = __napiModule.exports.OneHotEncoderParameters
module.exports.PCAF64 = __napiModule.exports.PCAF64
module.exports.PCAParameters = __napiModule.exports.PCAParameters
module.exports.PrecisionF64 = __napiModule.exports.PrecisionF64
module.exports.Precisionf64 = __napiModule.exports.Precisionf64
module.exports.R2F64 = __napiModule.exports.R2F64
module.exports.R2f64 = __napiModule.exports.R2f64
module.exports.R2I64 = __napiModule.exports.R2I64
module.exports.R2i64 = __napiModule.exports.R2i64
module.exports.RandomForestClassifierF64BigI64 = __napiModule.exports.RandomForestClassifierF64BigI64
module.exports.RandomForestClassifierF64I64 = __napiModule.exports.RandomForestClassifierF64I64
module.exports.RandomForestClassifierParameters = __napiModule.exports.RandomForestClassifierParameters
module.exports.RandomForestRegressorF64BigI64 = __napiModule.exports.RandomForestRegressorF64BigI64
module.exports.RandomForestRegressorF64F64 = __napiModule.exports.RandomForestRegressorF64F64
module.exports.RandomForestRegressorF64I64 = __napiModule.exports.RandomForestRegressorF64I64
module.exports.RandomForestRegressorParameters = __napiModule.exports.RandomForestRegressorParameters
module.exports.RecallF64 = __napiModule.exports.RecallF64
module.exports.Recallf64 = __napiModule.exports.Recallf64
module.exports.RidgeRegressionF64F64 = __napiModule.exports.RidgeRegressionF64F64
module.exports.RidgeRegressionParametersF64 = __napiModule.exports.RidgeRegressionParametersF64
module.exports.StandardScalerF64 = __napiModule.exports.StandardScalerF64
module.exports.StandardScalerParameters = __napiModule.exports.StandardScalerParameters
module.exports.SVCF64I64 = __napiModule.exports.SVCF64I64
module.exports.SVCParametersF64I64 = __napiModule.exports.SVCParametersF64I64
module.exports.SVDF64 = __napiModule.exports.SVDF64
module.exports.SVDF64DenseMatrixF64 = __napiModule.exports.SVDF64DenseMatrixF64
module.exports.SVDParameters = __napiModule.exports.SVDParameters
module.exports.SVRF64 = __napiModule.exports.SVRF64
module.exports.SVRParametersF64 = __napiModule.exports.SVRParametersF64
module.exports.VecF64 = __napiModule.exports.VecF64
module.exports.VecI64 = __napiModule.exports.VecI64
module.exports.crossValidateElasticNetF64F64 = __napiModule.exports.crossValidateElasticNetF64F64
module.exports.crossValidateElasticNetF64I64 = __napiModule.exports.crossValidateElasticNetF64I64
module.exports.crossValidateLogisticRegressionF64I64 = __napiModule.exports.crossValidateLogisticRegressionF64I64
module.exports.KNNAlgorithmName = __napiModule.exports.KNNAlgorithmName
module.exports.KNNWeightFunction = __napiModule.exports.KNNWeightFunction
module.exports.LinearRegressionSolverName = __napiModule.exports.LinearRegressionSolverName
module.exports.LogisticRegressionSolverName = __napiModule.exports.LogisticRegressionSolverName
module.exports.RidgeRegressionSolverName = __napiModule.exports.RidgeRegressionSolverName
module.exports.SplitCriterion = __napiModule.exports.SplitCriterion
module.exports.trainTestSplitF64BigI64 = __napiModule.exports.trainTestSplitF64BigI64
module.exports.trainTestSplitF64F64 = __napiModule.exports.trainTestSplitF64F64
module.exports.trainTestSplitF64I64 = __napiModule.exports.trainTestSplitF64I64
